/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.EventoController;
import com.iglesia.entities.Evento;
import com.iglesia.entities.Usuario;
import com.iglesia.enums.TipoBusquedaEnum;
import com.iglesia.utils.FechasUtils;
import java.awt.event.WindowEvent;
import javax.swing.JButton;

/**
 *
 * @author remsf
 */
public class DlgBuscarEvento extends javax.swing.JDialog {

    private final EventoController eventoController;
    private Evento evento;
    private Usuario usuarioLogeado;

    public void setUsuarioLogeado(Usuario usuarioLogeado) {
        this.usuarioLogeado = usuarioLogeado;
    }

    public Evento getEvento() {
        return evento;
    }

    /**
     * Creates new form DlgBuscarEvento
     */
    public DlgBuscarEvento(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.eventoController = new EventoController();
        this.txtfechaFin.setDate(FechasUtils.getCurrentDate());
        Object[] fechas = {FechasUtils.operateDate(FechasUtils.getCurrentDate(), -30), FechasUtils.getCurrentDate()};
        this.mostrarTabla(fechas, TipoBusquedaEnum.RANGO_FECHA);
    }

    private void mostrarTabla(Object[] filtro, TipoBusquedaEnum tipo) {
        this.eventoController.llenarTablaBusqueda(tbEvento, filtro, tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEvento = new javax.swing.JTable();
        jbCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnBuscar = new javax.swing.JButton();
        txtfechaInicio = new com.toedter.calendar.JDateChooser();
        txtfechaFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(520, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 129, 255)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbEvento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Lugar", "Sacerdote", "Sacramento", "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbEvento.setRowHeight(25);
        tbEvento.getTableHeader().setReorderingAllowed(false);
        tbEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEventoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEvento);
        if (tbEvento.getColumnModel().getColumnCount() > 0) {
            tbEvento.getColumnModel().getColumn(0).setMinWidth(30);
            tbEvento.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbEvento.getColumnModel().getColumn(0).setMaxWidth(45);
            tbEvento.getColumnModel().getColumn(1).setMinWidth(80);
            tbEvento.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbEvento.getColumnModel().getColumn(1).setMaxWidth(80);
            tbEvento.getColumnModel().getColumn(5).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(5).setMaxWidth(25);
            tbEvento.getColumnModel().getColumn(6).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(6).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(6).setMaxWidth(25);
            tbEvento.getColumnModel().getColumn(7).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(7).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(7).setMaxWidth(25);
            tbEvento.getColumnModel().getColumn(8).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(8).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(8).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 590, 290));

        jbCerrar.setBackground(new java.awt.Color(222, 62, 68));
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/cerrar-w.png"))); // NOI18N
        jbCerrar.setBorder(null);
        jbCerrar.setBorderPainted(false);
        jbCerrar.setContentAreaFilled(false);
        jbCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrar.setOpaque(true);
        jbCerrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbCerrarMouseMoved(evt);
            }
        });
        jbCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCerrarMouseExited(evt);
            }
        });
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 1, 30, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Busqueda de Evento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, -1));

        jbtnBuscar.setBackground(new java.awt.Color(107, 117, 125));
        jbtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/buscar.png"))); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.setBorder(null);
        jbtnBuscar.setBorderPainted(false);
        jbtnBuscar.setContentAreaFilled(false);
        jbtnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnBuscar.setOpaque(true);
        jbtnBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnBuscarMouseMoved(evt);
            }
        });
        jbtnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnBuscarMouseExited(evt);
            }
        });
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 85, 110, 40));

        txtfechaInicio.setBackground(new java.awt.Color(255, 255, 255));
        txtfechaInicio.setDateFormatString("dd/MM/yyyy");
        txtfechaInicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, -1));

        txtfechaFin.setBackground(new java.awt.Color(255, 255, 255));
        txtfechaFin.setDateFormatString("dd/MM/yyyy");
        txtfechaFin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 160, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/detalle.png"))); // NOI18N
        jLabel1.setText("Por defecto se mostraran los registros de los últimos 30 días.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 625, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEventoMouseClicked
        int column = this.tbEvento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.tbEvento.getRowHeight();

        if (row < this.tbEvento.getRowCount() && row >= 0
                && column < this.tbEvento.getColumnCount() && column >= 0) {
            Object value = this.tbEvento.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                Integer id = Integer.parseInt(this.tbEvento.getValueAt(row, 0).toString());
                if (column == 5) {
                    DlgDetalleEvento obj = new DlgDetalleEvento(this, true, id);
                    obj.setVisible(true);
                } else if (column == 6) {
                    this.evento = this.eventoController.consultarPorId(id);
                    if (this.evento != null) {
                        this.eventoController.generarRpt(this.evento);
                    }
                } else if (column == 7) {
                    this.evento = this.eventoController.consultarPorId(id);
                    if (this.evento != null) {
                        this.eventoController.generarRptConstancia(this.evento);
                    }
                } else if (column == 8) {
                    this.evento = this.eventoController.consultarPorId(id);
                    this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                }
            }
        }
    }//GEN-LAST:event_tbEventoMouseClicked

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        if (this.txtfechaInicio.getDate() == null || this.txtfechaFin.getDate() == null) {
            DlgWindow.showMessageDialog(this, "Aviso", "Es necesario seleccionar un rango de fechas.", DlgWindow.WARN);
            return;
        }
        Object[] obj = {this.txtfechaInicio.getDate(), this.txtfechaFin.getDate()};
        this.mostrarTabla(obj, TipoBusquedaEnum.RANGO_FECHA);
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarMouseMoved
        this.jbtnBuscar.setBackground(new java.awt.Color(132, 142, 149));
    }//GEN-LAST:event_jbtnBuscarMouseMoved

    private void jbtnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBuscarMouseExited
        this.jbtnBuscar.setBackground(new java.awt.Color(107, 117, 125));
    }//GEN-LAST:event_jbtnBuscarMouseExited

    private void jbCerrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarMouseMoved
        this.jbCerrar.setBackground(new java.awt.Color(227, 96, 101));
    }//GEN-LAST:event_jbCerrarMouseMoved

    private void jbCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarMouseExited
        this.jbCerrar.setBackground(new java.awt.Color(222, 62, 68));
    }//GEN-LAST:event_jbCerrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBuscarEvento dialog = new DlgBuscarEvento(new javax.swing.JDialog(), true
                );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JTable tbEvento;
    private com.toedter.calendar.JDateChooser txtfechaFin;
    private com.toedter.calendar.JDateChooser txtfechaInicio;
    // End of variables declaration//GEN-END:variables
}
