/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.EventoController;
import com.iglesia.controllers.ResponsableEventoController;
import com.iglesia.entities.Evento;
import com.iglesia.enums.TipoBusquedaEnum;
import com.iglesia.utils.FechasUtils;
import java.awt.Color;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author remsf
 */
public class DlgBuscarEvento extends javax.swing.JDialog {
    
    private final EventoController eventoController;
    private final ResponsableEventoController responsableEventoController;
    private Evento evento;
    
    public Evento getEvento() {
        return evento;
    }

    /**
     * Creates new form DlgBuscarEvento
     */
    public DlgBuscarEvento(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.eventoController = new EventoController();
        this.responsableEventoController = new ResponsableEventoController();
        this.jPanel1.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        this.txtfechaFin.setDate(FechasUtils.getCurrentDate());
    }
    
    private void mostrarTabla(Object[] filtro, TipoBusquedaEnum tipo) {
        this.eventoController.llenarTablaBusqueda(tbEvento, filtro, tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEvento = new javax.swing.JTable();
        jbCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtfechaInicio = new com.toedter.calendar.JDateChooser();
        txtfechaFin = new com.toedter.calendar.JDateChooser();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(520, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(55, 71, 79));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Lugar", "Sacerdote", "Sacramento", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEvento.setRowHeight(25);
        tbEvento.getTableHeader().setReorderingAllowed(false);
        tbEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEventoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbEvento);
        if (tbEvento.getColumnModel().getColumnCount() > 0) {
            tbEvento.getColumnModel().getColumn(0).setMinWidth(30);
            tbEvento.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbEvento.getColumnModel().getColumn(0).setMaxWidth(45);
            tbEvento.getColumnModel().getColumn(1).setMinWidth(80);
            tbEvento.getColumnModel().getColumn(1).setPreferredWidth(80);
            tbEvento.getColumnModel().getColumn(1).setMaxWidth(80);
            tbEvento.getColumnModel().getColumn(5).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(5).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(5).setMaxWidth(25);
            tbEvento.getColumnModel().getColumn(6).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(6).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(6).setMaxWidth(25);
            tbEvento.getColumnModel().getColumn(7).setMinWidth(25);
            tbEvento.getColumnModel().getColumn(7).setPreferredWidth(25);
            tbEvento.getColumnModel().getColumn(7).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 590, 290));

        jbCerrar.setBackground(new java.awt.Color(204, 0, 0));
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("X");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, 32));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Busqueda de Evento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, -1));

        jButton1.setBackground(new java.awt.Color(0, 126, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 65, 110, -1));

        txtfechaInicio.setDateFormatString("dd/MM/yyyy");
        txtfechaInicio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, -1));

        txtfechaFin.setDateFormatString("dd/MM/yyyy");
        txtfechaFin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEventoMouseClicked
        int column = this.tbEvento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / this.tbEvento.getRowHeight();
        
        if (row < this.tbEvento.getRowCount() && row >= 0
                && column < this.tbEvento.getColumnCount() && column >= 0) {
            Object value = this.tbEvento.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                Integer id = Integer.parseInt(this.tbEvento.getValueAt(row, 0).toString());
                if (column == 5) {
                    DlgDetalleEvento obj = new DlgDetalleEvento(this, true, id);
                    obj.setVisible(true);
                } else if (column == 6) {
                    this.evento = this.eventoController.consultarPorId(id);
                    if (this.evento != null) {
                        this.eventoController.generarRpt(this.evento);
                    }
                } else if (column == 7) {
                    this.evento = this.eventoController.consultarPorId(id);
                    if (this.evento != null) {
                        this.eventoController.generarRptConstancia(this.evento);
                    }
                }
            }
        }
    }//GEN-LAST:event_tbEventoMouseClicked

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.txtfechaInicio.getDate() == null || this.txtfechaFin.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Es necesario seleccionar un rango de fechas.","Aviso",JOptionPane.WARNING_MESSAGE);
            return;
        }
        Object[] obj = {this.txtfechaInicio.getDate(), this.txtfechaFin.getDate()};
        this.mostrarTabla(obj, TipoBusquedaEnum.RANGO_FECHA);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgBuscarEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBuscarEvento dialog = new DlgBuscarEvento(new javax.swing.JDialog(), true
                );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JTable tbEvento;
    private com.toedter.calendar.JDateChooser txtfechaFin;
    private com.toedter.calendar.JDateChooser txtfechaInicio;
    // End of variables declaration//GEN-END:variables
}
