/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.BodaController;
import com.iglesia.controllers.EventoController;
import com.iglesia.utils.ProjectUtils;
import java.awt.Color;
import java.awt.Shape;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author remsf
 */
public class DlgBoda extends javax.swing.JDialog {

    private final EventoController eventoCtrl;
    Shape dialogShape;

    /**
     * Creates new form DlgBoda
     */
    public DlgBoda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);        
        this.eventoCtrl = new EventoController();                
        this.jPanel1.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
        this.txtTomo.requestFocus();
    }

    private void setOrderTab() {

    }

//    private void onlyRead() {
//        this.txtNovio.setEditable(false);
//        this.txtPadreNovio.setEditable(false);
//        this.txtMadreNovio.setEditable(false);
//        this.txtNovia.setEditable(false);
//        this.txtPadreNovia.setEditable(false);
//        this.txtMadreNovia.setEditable(false);
//    }
//    @Override
//    public void paint(Graphics g) {
//        super.paint(g);
//        AWTUtilities.setWindowShape(this, dialogShape);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTomo = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        txtLugar = new javax.swing.JTextField();
        btnBuscarLugar = new javax.swing.JButton();
        txtNovio = new javax.swing.JTextField();
        btnBuscarNovio = new javax.swing.JButton();
        txtPadreNovio = new javax.swing.JTextField();
        btnBuscarPadreNovio = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtMadreNovio = new javax.swing.JTextField();
        btnBuscarMadreNovio = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNovia = new javax.swing.JTextField();
        btnBuscarNovia = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPadreNovia = new javax.swing.JTextField();
        btnBuscarPadreNovia = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtMadreNovia = new javax.swing.JTextField();
        btnBuscarMadreNovia = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTestigo1 = new javax.swing.JTextField();
        btnBuscarTestigo1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtSacerdote = new javax.swing.JTextField();
        btnBuscarSacerdote = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtTestigo2 = new javax.swing.JTextField();
        btnBuscarTestigo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(55, 71, 79));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tomo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Folio");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha del evento");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Número");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Lugar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Novio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Padre del Novio");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jbCerrar.setBackground(new java.awt.Color(204, 0, 0));
        jbCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrar.setText("X");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jbCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 32));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Boda");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
        jPanel1.add(txtTomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 100, -1));
        jPanel1.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 100, -1));
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 130, -1));

        txtLugar.setEditable(false);
        jPanel1.add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, -1));

        btnBuscarLugar.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarLugar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarLugar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarLugar.setText("Buscar");
        btnBuscarLugar.setToolTipText("Buscar novio");
        btnBuscarLugar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 30));

        txtNovio.setEditable(false);
        jPanel1.add(txtNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 200, -1));

        btnBuscarNovio.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarNovio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarNovio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarNovio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarNovio.setText("Buscar");
        btnBuscarNovio.setToolTipText("Buscar novio");
        btnBuscarNovio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNovioActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, 30));

        txtPadreNovio.setEditable(false);
        jPanel1.add(txtPadreNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 200, -1));

        btnBuscarPadreNovio.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarPadreNovio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarPadreNovio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPadreNovio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarPadreNovio.setText("Buscar");
        btnBuscarPadreNovio.setToolTipText("Buscar padre de novio");
        btnBuscarPadreNovio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarPadreNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPadreNovioActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPadreNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Madre del Novio");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        txtMadreNovio.setEditable(false);
        jPanel1.add(txtMadreNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 200, -1));

        btnBuscarMadreNovio.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarMadreNovio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarMadreNovio.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMadreNovio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarMadreNovio.setText("Buscar");
        btnBuscarMadreNovio.setToolTipText("Buscar madre de novio");
        btnBuscarMadreNovio.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarMadreNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMadreNovioActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMadreNovio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Novia");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        txtNovia.setEditable(false);
        txtNovia.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, -1));

        btnBuscarNovia.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarNovia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarNovia.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarNovia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarNovia.setText("Buscar");
        btnBuscarNovia.setToolTipText("Buscar novia");
        btnBuscarNovia.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarNovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNoviaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Padre Novia");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        txtPadreNovia.setEditable(false);
        jPanel1.add(txtPadreNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 200, -1));

        btnBuscarPadreNovia.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarPadreNovia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarPadreNovia.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPadreNovia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarPadreNovia.setText("Buscar");
        btnBuscarPadreNovia.setToolTipText("Buscar padre de novia");
        btnBuscarPadreNovia.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarPadreNovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPadreNoviaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarPadreNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, -1, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Madre Novia");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        txtMadreNovia.setEditable(false);
        jPanel1.add(txtMadreNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 200, -1));

        btnBuscarMadreNovia.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarMadreNovia.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarMadreNovia.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMadreNovia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarMadreNovia.setText("Buscar");
        btnBuscarMadreNovia.setToolTipText("Buscar madre de novia");
        btnBuscarMadreNovia.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarMadreNovia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMadreNoviaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarMadreNovia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Testigo");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        txtTestigo1.setEditable(false);
        jPanel1.add(txtTestigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 200, -1));

        btnBuscarTestigo1.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarTestigo1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarTestigo1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTestigo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarTestigo1.setText("Buscar");
        btnBuscarTestigo1.setToolTipText("Buscar madre de novia");
        btnBuscarTestigo1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarTestigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTestigo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarTestigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sacerdote");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        txtSacerdote.setEditable(false);
        jPanel1.add(txtSacerdote, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 200, -1));

        btnBuscarSacerdote.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarSacerdote.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarSacerdote.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarSacerdote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarSacerdote.setText("Buscar");
        btnBuscarSacerdote.setToolTipText("Buscar madre de novia");
        btnBuscarSacerdote.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarSacerdote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSacerdoteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarSacerdote, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, 30));

        btnGuardar.setBackground(new java.awt.Color(13, 71, 161));
        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 130, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 136, 0));
        btnCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-cancelar_azul.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 460, 130, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Testigo");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        txtTestigo2.setEditable(false);
        jPanel1.add(txtTestigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 200, -1));

        btnBuscarTestigo2.setBackground(new java.awt.Color(0, 126, 51));
        btnBuscarTestigo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarTestigo2.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarTestigo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/x26-buscar.png"))); // NOI18N
        btnBuscarTestigo2.setText("Buscar");
        btnBuscarTestigo2.setToolTipText("Buscar madre de novia");
        btnBuscarTestigo2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnBuscarTestigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTestigo2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarTestigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void btnBuscarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLugarActionPerformed
        DlgBuscarLugar obj = new DlgBuscarLugar(this, true);
        obj.setVisible(true);
        if (obj.getLugar() != null) {
            this.eventoCtrl.getDtoSelected().setLugar(obj.getLugar());
            this.txtLugar.setText(this.eventoCtrl.getDtoSelected().getLugar().getNombre());
        }
    }//GEN-LAST:event_btnBuscarLugarActionPerformed

    private void btnBuscarNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNovioActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setNovio(obj.getPersona());
            this.txtNovio.setText(this.eventoCtrl.getDtoSelected().getNovio().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarNovioActionPerformed

    private void btnBuscarPadreNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPadreNovioActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setPadreNovio(obj.getPersona());
            this.txtPadreNovio.setText(this.eventoCtrl.getDtoSelected().getPadreNovio().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarPadreNovioActionPerformed

    private void btnBuscarMadreNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMadreNovioActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setMadreNovio(obj.getPersona());
            this.txtMadreNovio.setText(this.eventoCtrl.getDtoSelected().getMadreNovio().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarMadreNovioActionPerformed

    private void btnBuscarNoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNoviaActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setNovia(obj.getPersona());
            this.txtNovia.setText(this.eventoCtrl.getDtoSelected().getNovia().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarNoviaActionPerformed

    private void btnBuscarPadreNoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPadreNoviaActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setPadreNovia(obj.getPersona());
            this.txtPadreNovia.setText(this.eventoCtrl.getDtoSelected().getPadreNovia().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarPadreNoviaActionPerformed

    private void btnBuscarMadreNoviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMadreNoviaActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setMadreNovia(obj.getPersona());
            this.txtMadreNovia.setText(this.eventoCtrl.getDtoSelected().getMadreNovia().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarMadreNoviaActionPerformed

    private void btnBuscarTestigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTestigo1ActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setTestigo1(obj.getPersona());
            this.txtTestigo1.setText(this.eventoCtrl.getDtoSelected().getTestigo1().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarTestigo1ActionPerformed

    private void btnBuscarSacerdoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSacerdoteActionPerformed
        DlgBuscarSacerdote obj = new DlgBuscarSacerdote(this, true);
        obj.setVisible(true);
        if (obj.getSacerdote() != null) {
            this.eventoCtrl.getDtoSelected().setSacerdote(obj.getSacerdote());
            this.txtSacerdote.setText(this.eventoCtrl.getDtoSelected().getSacerdote().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarSacerdoteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de realizar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION) == 0) {
            this.eventoCtrl.getDtoSelected().setTomo(this.txtTomo.getText());
            this.eventoCtrl.getDtoSelected().setFolio(this.txtFolio.getText());
            this.eventoCtrl.getDtoSelected().setNumero(this.txtNumero.getText());
            this.eventoCtrl.getDtoSelected().setFecha(this.txtFecha.getDate());
            this.crear();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void crear() {        
        if (ProjectUtils.validarVacios(this.jPanel1, null)) {
            JOptionPane.showMessageDialog(this, "Campo(s) Requerido(s) vacio(s)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (this.eventoCtrl.registrarEvento(new BodaController())) {
            JOptionPane.showMessageDialog(this, "Registro realizado correctamente.!", "Información", JOptionPane.INFORMATION_MESSAGE);
            ProjectUtils.limpiarComponentes(this.jPanel1);
        } else {
            JOptionPane.showMessageDialog(this, "Error al realizar el registro.!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnBuscarTestigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTestigo2ActionPerformed
        DlgBuscarPersona obj = new DlgBuscarPersona(this, true);
        obj.setVisible(true);
        if (obj.getPersona() != null) {
            this.eventoCtrl.getDtoSelected().setTestigo2(obj.getPersona());
            this.txtTestigo2.setText(this.eventoCtrl.getDtoSelected().getTestigo2().getNombreCompleto());
        }
    }//GEN-LAST:event_btnBuscarTestigo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgBoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgBoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgBoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgBoda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBoda dialog = new DlgBoda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarLugar;
    private javax.swing.JButton btnBuscarMadreNovia;
    private javax.swing.JButton btnBuscarMadreNovio;
    private javax.swing.JButton btnBuscarNovia;
    private javax.swing.JButton btnBuscarNovio;
    private javax.swing.JButton btnBuscarPadreNovia;
    private javax.swing.JButton btnBuscarPadreNovio;
    private javax.swing.JButton btnBuscarSacerdote;
    private javax.swing.JButton btnBuscarTestigo1;
    private javax.swing.JButton btnBuscarTestigo2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCerrar;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtMadreNovia;
    private javax.swing.JTextField txtMadreNovio;
    private javax.swing.JTextField txtNovia;
    private javax.swing.JTextField txtNovio;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPadreNovia;
    private javax.swing.JTextField txtPadreNovio;
    private javax.swing.JTextField txtSacerdote;
    private javax.swing.JTextField txtTestigo1;
    private javax.swing.JTextField txtTestigo2;
    private javax.swing.JTextField txtTomo;
    // End of variables declaration//GEN-END:variables
}
