/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.PersonaController;
import com.iglesia.entities.Persona;
import com.iglesia.utils.TextPrompt;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;

/**
 *
 * @author Alexis
 */
public class DlgConsultaPersona extends javax.swing.JDialog {

    /**
     * Creates new form DlgPersona
     */
    private PersonaController personaController;
    private List<String> excepciones = new ArrayList<>();

    public DlgConsultaPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.personaController = new PersonaController();
        // comienza generacion de campos formateados
        // termina generacion de campos formateados
        this.setLocationRelativeTo(null);
        this.excepciones.add("buscar");
        this.excepciones.add("dui");
        this.excepciones.add("nit");
        this.mostrarTabla("");
        new TextPrompt("Digite para buscar en nombres o apellidos", this.txtbuscar);
        this.jPanel1.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
    }

    private void mostrarTabla(String filtro) {
        this.personaController.llenarTabla(tbpersona, filtro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGenero = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpersona = new javax.swing.JTable();
        txtbuscar = new javax.swing.JTextField();
        btnNuevaPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(55, 71, 79));
        jPanel1.setForeground(new java.awt.Color(189, 189, 189));
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Personas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 940, -1));

        btnSalir.setBackground(new java.awt.Color(204, 0, 0));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/cancel.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 32));

        tbpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "DUI", "NIT", "F.Nacimiento", "Direccion", "Genero", "Estado", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbpersona.setRowHeight(25);
        tbpersona.getTableHeader().setReorderingAllowed(false);
        tbpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpersonaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbpersona);
        if (tbpersona.getColumnModel().getColumnCount() > 0) {
            tbpersona.getColumnModel().getColumn(0).setMinWidth(40);
            tbpersona.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbpersona.getColumnModel().getColumn(0).setMaxWidth(40);
            tbpersona.getColumnModel().getColumn(3).setMinWidth(85);
            tbpersona.getColumnModel().getColumn(3).setPreferredWidth(85);
            tbpersona.getColumnModel().getColumn(3).setMaxWidth(85);
            tbpersona.getColumnModel().getColumn(4).setMinWidth(120);
            tbpersona.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbpersona.getColumnModel().getColumn(4).setMaxWidth(120);
            tbpersona.getColumnModel().getColumn(5).setMinWidth(85);
            tbpersona.getColumnModel().getColumn(5).setPreferredWidth(85);
            tbpersona.getColumnModel().getColumn(5).setMaxWidth(85);
            tbpersona.getColumnModel().getColumn(7).setMinWidth(50);
            tbpersona.getColumnModel().getColumn(7).setPreferredWidth(50);
            tbpersona.getColumnModel().getColumn(7).setMaxWidth(50);
            tbpersona.getColumnModel().getColumn(8).setMinWidth(60);
            tbpersona.getColumnModel().getColumn(8).setPreferredWidth(60);
            tbpersona.getColumnModel().getColumn(8).setMaxWidth(60);
            tbpersona.getColumnModel().getColumn(9).setMinWidth(25);
            tbpersona.getColumnModel().getColumn(9).setPreferredWidth(25);
            tbpersona.getColumnModel().getColumn(9).setMaxWidth(25);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 900, 500));

        txtbuscar.setName("buscar"); // NOI18N
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 380, -1));

        btnNuevaPersona.setBackground(new java.awt.Color(108, 117, 125));
        btnNuevaPersona.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNuevaPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/agregar.png"))); // NOI18N
        btnNuevaPersona.setText("Nueva persona");
        btnNuevaPersona.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNuevaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPersonaActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 75, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        this.mostrarTabla(this.txtbuscar.getText());
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tbpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpersonaMouseClicked
        int column = this.tbpersona.getColumnModel().getColumnIndexAtX(evt.getX());
        // columna 9 es donde se encuentra el boton de editar
        if (column != 9) {
            return;
        }
//        int row = evt.getY() / this.tbpersona.getRowHeight();
        int row= tbpersona.getSelectedRow();

        if (row < this.tbpersona.getRowCount() && row >= 0
                && column < this.tbpersona.getColumnCount() && column >= 0) {
            Object value = this.tbpersona.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                Integer id = Integer.parseInt(this.tbpersona.getValueAt(row, 0).toString());
                Persona selected = this.personaController.consultarPorId(id);
                DlgPersona obj = new DlgPersona(null,true);
                obj.setPersonaToEdit(selected);
                obj.setVisible(true);
                this.mostrarTabla("");
            }
        }
    }//GEN-LAST:event_tbpersonaMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaPersonaActionPerformed
        DlgPersona obj = new DlgPersona(null, true);
        obj.setRedirect(false);
        obj.setVisible(true);
        this.mostrarTabla("");
    }//GEN-LAST:event_btnNuevaPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConsultaPersona dialog = new DlgConsultaPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGenero;
    private javax.swing.JButton btnNuevaPersona;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbpersona;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
