/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.LugarController;
import com.iglesia.controllers.PersonaController;
import com.iglesia.entities.Lugar;
import com.iglesia.entities.Persona;
import com.iglesia.utils.AutoComplete;
import com.iglesia.utils.TextPrompt;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author remsf
 */
public class DlgPruebaAutoComplete extends javax.swing.JDialog {

    private final PersonaController personaCtrl;
    private final LugarController lugarCtrl;
    private List<Persona> personas;
    private final AutoComplete ac;
    private final AutoComplete acLugar;
    private Persona selected;
    private Lugar lugar;

    /**
     * Creates new form DlgPruebaAutoComplete
     */
    public DlgPruebaAutoComplete(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        new TextPrompt("digite nombre para buscar", this.txtBuscar);
        new TextPrompt("digite nombre de lugar para buscar", this.txtLugar);
        this.personaCtrl = new PersonaController();
        this.lugarCtrl = new LugarController();
        this.ac = new AutoComplete(this.txtBuscar, "getNombreCompleto");
        this.acLugar = new AutoComplete(this.txtLugar, "getNombre");
        this.personaCtrl.consultarTodos();
        this.personaCtrl.getItems().forEach((item) -> {
            this.ac.addElement(item);
        });
        this.lugarCtrl.consultarTodos();
        this.lugarCtrl.getItems().forEach((item) -> {
            this.acLugar.addElement(item);
        });
//        ac.setListData(this.personaCtrl.getItems().toArray());
//        this.listaPer.setListData(this.personaCtrl.getItems().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtLugar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLugarKeyReleased(evt);
            }
        });
        jPanel1.add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 280, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        this.ac.filterListItems();
        this.selected = (Persona) this.ac.getSelected();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.selected = (Persona) this.ac.getSelected();
        this.lugar = (Lugar) this.acLugar.getSelected();
        JOptionPane.showMessageDialog(null, "el valor seleccionado es= " + this.selected.getNombreCompleto() + ", lugar= " + this.lugar.getNombre());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtLugarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyReleased
        this.acLugar.filterListItems();
    }//GEN-LAST:event_txtLugarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgPruebaAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgPruebaAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgPruebaAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgPruebaAutoComplete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgPruebaAutoComplete dialog = new DlgPruebaAutoComplete(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtLugar;
    // End of variables declaration//GEN-END:variables
}
