/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.entities.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author remsf
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private boolean visible;
    private Usuario usuario;
    
    public Usuario getUsuario() {
        return usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        this.jlblUsuario.setText(this.usuario.getNombre() + " " + this.usuario.getApellido());
    }

    /**
     * Creates new form PrincipalFrame
     */
    public FrmPrincipal() {
        initComponents();
        this.visible = true;
        this.setExtendedState(MAXIMIZED_BOTH);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanio = tk.getScreenSize();
//        this.panelTop.setBounds(0, 0, (int) tamanio.getWidth(), 50);
        getContentPane().add(panelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, (int) tamanio.getWidth(), 40));
        int positionBtnClose = (int) tamanio.getWidth() - 31;
        panelTop.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(positionBtnClose, 0, 30, 40));
        panelTop.add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(positionBtnClose - 220, 0, 250, 40));
        panelTop.add(jlblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(positionBtnClose - 250, 0, 250, 40));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnSector = new javax.swing.JButton();
        btnSacerdotes = new javax.swing.JButton();
        btnComunidad = new javax.swing.JButton();
        btnJustificacion = new javax.swing.JButton();
        btnTipoSacramento = new javax.swing.JButton();
        btnLugar = new javax.swing.JButton();
        btnConsultaPersonas = new javax.swing.JButton();
        btnPersona1 = new javax.swing.JButton();
        btnEvento = new javax.swing.JButton();
        btnNuevoMovEfectivo = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        panelTop = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jlblUsuario = new javax.swing.JLabel();
        jlblIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConsultarMovEfectivoTop = new javax.swing.JButton();
        btnBautizoTop = new javax.swing.JButton();
        btnConfirmacionTop = new javax.swing.JButton();
        btnBodaTop = new javax.swing.JButton();
        btnCatalogos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(870, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));

        btnSector.setBackground(new java.awt.Color(0, 153, 204));
        btnSector.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSector.setForeground(new java.awt.Color(255, 255, 255));
        btnSector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/server-rack-36px.png"))); // NOI18N
        btnSector.setText("Sector");
        btnSector.setBorder(null);
        btnSector.setBorderPainted(false);
        btnSector.setContentAreaFilled(false);
        btnSector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSector.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSector.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSector.setOpaque(true);
        btnSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSectorActionPerformed(evt);
            }
        });

        btnSacerdotes.setBackground(new java.awt.Color(0, 153, 204));
        btnSacerdotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSacerdotes.setForeground(new java.awt.Color(255, 255, 255));
        btnSacerdotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/padre-36px.png"))); // NOI18N
        btnSacerdotes.setText("Sacerdotes");
        btnSacerdotes.setBorder(null);
        btnSacerdotes.setBorderPainted(false);
        btnSacerdotes.setContentAreaFilled(false);
        btnSacerdotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSacerdotes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSacerdotes.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSacerdotes.setOpaque(true);
        btnSacerdotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacerdotesActionPerformed(evt);
            }
        });

        btnComunidad.setBackground(new java.awt.Color(0, 153, 204));
        btnComunidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnComunidad.setForeground(new java.awt.Color(255, 255, 255));
        btnComunidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/server-rack-36px.png"))); // NOI18N
        btnComunidad.setText("Comunidad");
        btnComunidad.setBorder(null);
        btnComunidad.setBorderPainted(false);
        btnComunidad.setContentAreaFilled(false);
        btnComunidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComunidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnComunidad.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnComunidad.setOpaque(true);
        btnComunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComunidadActionPerformed(evt);
            }
        });

        btnJustificacion.setBackground(new java.awt.Color(0, 153, 204));
        btnJustificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnJustificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnJustificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/server-rack-36px.png"))); // NOI18N
        btnJustificacion.setText("Justificación");
        btnJustificacion.setBorder(null);
        btnJustificacion.setBorderPainted(false);
        btnJustificacion.setContentAreaFilled(false);
        btnJustificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJustificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnJustificacion.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnJustificacion.setOpaque(true);
        btnJustificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJustificacionActionPerformed(evt);
            }
        });

        btnTipoSacramento.setBackground(new java.awt.Color(0, 153, 204));
        btnTipoSacramento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTipoSacramento.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoSacramento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/server-rack-36px.png"))); // NOI18N
        btnTipoSacramento.setText("Tipo de Sacramento");
        btnTipoSacramento.setBorder(null);
        btnTipoSacramento.setBorderPainted(false);
        btnTipoSacramento.setContentAreaFilled(false);
        btnTipoSacramento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTipoSacramento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnTipoSacramento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnTipoSacramento.setOpaque(true);
        btnTipoSacramento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSacramentoActionPerformed(evt);
            }
        });

        btnLugar.setBackground(new java.awt.Color(0, 153, 204));
        btnLugar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLugar.setForeground(new java.awt.Color(255, 255, 255));
        btnLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/server-rack-36px.png"))); // NOI18N
        btnLugar.setText("Lugar");
        btnLugar.setBorder(null);
        btnLugar.setBorderPainted(false);
        btnLugar.setContentAreaFilled(false);
        btnLugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnLugar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnLugar.setOpaque(true);
        btnLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugarActionPerformed(evt);
            }
        });

        btnConsultaPersonas.setBackground(new java.awt.Color(0, 153, 204));
        btnConsultaPersonas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultaPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/folder-person-w-36px.png"))); // NOI18N
        btnConsultaPersonas.setText("Consulta de personas");
        btnConsultaPersonas.setBorder(null);
        btnConsultaPersonas.setBorderPainted(false);
        btnConsultaPersonas.setContentAreaFilled(false);
        btnConsultaPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultaPersonas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnConsultaPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnConsultaPersonas.setOpaque(true);
        btnConsultaPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaPersonasActionPerformed(evt);
            }
        });

        btnPersona1.setBackground(new java.awt.Color(0, 153, 204));
        btnPersona1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPersona1.setForeground(new java.awt.Color(255, 255, 255));
        btnPersona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/add-persona-w-36px.png"))); // NOI18N
        btnPersona1.setText("Registrar nueva persona");
        btnPersona1.setBorder(null);
        btnPersona1.setBorderPainted(false);
        btnPersona1.setContentAreaFilled(false);
        btnPersona1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersona1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnPersona1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnPersona1.setOpaque(true);
        btnPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersona1ActionPerformed(evt);
            }
        });

        btnEvento.setBackground(new java.awt.Color(0, 153, 204));
        btnEvento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/boda-36px.png"))); // NOI18N
        btnEvento.setText("Evento");
        btnEvento.setBorder(null);
        btnEvento.setBorderPainted(false);
        btnEvento.setContentAreaFilled(false);
        btnEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnEvento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnEvento.setOpaque(true);
        btnEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventoActionPerformed(evt);
            }
        });

        btnNuevoMovEfectivo.setBackground(new java.awt.Color(0, 153, 204));
        btnNuevoMovEfectivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevoMovEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMovEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/dolar-hand-w-36px.png"))); // NOI18N
        btnNuevoMovEfectivo.setText("Crear mov. de efectivo");
        btnNuevoMovEfectivo.setBorder(null);
        btnNuevoMovEfectivo.setBorderPainted(false);
        btnNuevoMovEfectivo.setContentAreaFilled(false);
        btnNuevoMovEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoMovEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnNuevoMovEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevoMovEfectivo.setOpaque(true);
        btnNuevoMovEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoMovEfectivoActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(0, 153, 204));
        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/users-w-36px.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnUsuarios.setOpaque(true);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultaPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComunidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPersona1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTipoSacramento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJustificacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSacerdotes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevoMovEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTipoSacramento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnJustificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSector, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacerdotes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevoMovEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 1040));

        panelTop.setBackground(new java.awt.Color(0, 129, 255));
        panelTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(0, 129, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/menu-36px.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setOpaque(true);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        panelTop.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, -1, 35));

        btnSalir.setBackground(new java.awt.Color(0, 129, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/cerrar.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setOpaque(true);
        btnSalir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSalirMouseMoved(evt);
            }
        });
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelTop.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 30, 40));

        jlblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlblUsuario.setText("jLabel1");
        panelTop.add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 250, 40));

        jlblIconUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblIconUser.setForeground(new java.awt.Color(105, 105, 105));
        jlblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/user-shape-w-24px.png"))); // NOI18N
        panelTop.add(jlblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 30, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE CONTROL PARROQUIAL");
        panelTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 350, 40));

        getContentPane().add(panelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 40));

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConsultarMovEfectivoTop.setBackground(new java.awt.Color(27, 163, 69));
        btnConsultarMovEfectivoTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarMovEfectivoTop.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarMovEfectivoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/dolar-arrows-w-36px.png"))); // NOI18N
        btnConsultarMovEfectivoTop.setText("Mov. de efectivo");
        btnConsultarMovEfectivoTop.setBorder(null);
        btnConsultarMovEfectivoTop.setBorderPainted(false);
        btnConsultarMovEfectivoTop.setContentAreaFilled(false);
        btnConsultarMovEfectivoTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultarMovEfectivoTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarMovEfectivoTop.setOpaque(true);
        btnConsultarMovEfectivoTop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarMovEfectivoTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarMovEfectivoTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarMovEfectivoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 0, 120, 60));

        btnBautizoTop.setBackground(new java.awt.Color(27, 163, 69));
        btnBautizoTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBautizoTop.setForeground(new java.awt.Color(255, 255, 255));
        btnBautizoTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/confirmacion-36px.png"))); // NOI18N
        btnBautizoTop.setText("Bautizo");
        btnBautizoTop.setBorder(null);
        btnBautizoTop.setBorderPainted(false);
        btnBautizoTop.setContentAreaFilled(false);
        btnBautizoTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBautizoTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBautizoTop.setOpaque(true);
        btnBautizoTop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBautizoTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBautizoTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnBautizoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 120, 60));

        btnConfirmacionTop.setBackground(new java.awt.Color(27, 163, 69));
        btnConfirmacionTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmacionTop.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmacionTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/confirmacion-36px.png"))); // NOI18N
        btnConfirmacionTop.setText("Confirmación");
        btnConfirmacionTop.setBorder(null);
        btnConfirmacionTop.setBorderPainted(false);
        btnConfirmacionTop.setContentAreaFilled(false);
        btnConfirmacionTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmacionTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmacionTop.setOpaque(true);
        btnConfirmacionTop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfirmacionTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmacionTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfirmacionTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 0, 120, 60));

        btnBodaTop.setBackground(new java.awt.Color(27, 163, 69));
        btnBodaTop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBodaTop.setForeground(new java.awt.Color(255, 255, 255));
        btnBodaTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/boda-36px.png"))); // NOI18N
        btnBodaTop.setText("Boda");
        btnBodaTop.setBorder(null);
        btnBodaTop.setBorderPainted(false);
        btnBodaTop.setContentAreaFilled(false);
        btnBodaTop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBodaTop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBodaTop.setOpaque(true);
        btnBodaTop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBodaTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBodaTopActionPerformed(evt);
            }
        });
        jPanel1.add(btnBodaTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 120, 60));

        btnCatalogos.setBackground(new java.awt.Color(27, 163, 69));
        btnCatalogos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCatalogos.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/menu-36px.png"))); // NOI18N
        btnCatalogos.setText("Catalogos");
        btnCatalogos.setBorder(null);
        btnCatalogos.setBorderPainted(false);
        btnCatalogos.setContentAreaFilled(false);
        btnCatalogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCatalogos.setOpaque(true);
        btnCatalogos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCatalogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogosActionPerformed(evt);
            }
        });
        jPanel1.add(btnCatalogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 40, 630, 60));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacerdotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacerdotesActionPerformed
        DlgSacerdote obj = new DlgSacerdote(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnSacerdotesActionPerformed

    private void btnSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSectorActionPerformed
        DlgSector obj = new DlgSector(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnSectorActionPerformed

    private void btnComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComunidadActionPerformed
        DlgComunidad obj = new DlgComunidad(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnComunidadActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        //-220
        if (this.panelMenu.getX() == 0) {
            Animacion.Animacion.mover_izquierda(0, -185, 10, 5, this.panelMenu);
//            Animacion.Animacion.mover_izquierda(190, 0, 10, 5, this.btnMenu);
        } else {
            Animacion.Animacion.mover_derecha(this.panelMenu.getX(), 0, 10, 5, this.panelMenu);
//            Animacion.Animacion.mover_derecha(0, 190, 10, 5, this.btnMenu);
        }

    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnJustificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJustificacionActionPerformed
        DlgJustificacion obj = new DlgJustificacion(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnJustificacionActionPerformed

    private void btnTipoSacramentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSacramentoActionPerformed
        DlgTipoSacrementos obj = new DlgTipoSacrementos(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnTipoSacramentoActionPerformed

    private void btnLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugarActionPerformed
        DlgLugar obj = new DlgLugar(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnLugarActionPerformed

    private void btnConsultaPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaPersonasActionPerformed
        DlgConsultaPersona obj = new DlgConsultaPersona(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnConsultaPersonasActionPerformed

    private void btnPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersona1ActionPerformed
        DlgPersona obj = new DlgPersona(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnPersona1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        if (DlgWindow.showConfirmDialog(null, "Confirmación", "¿Esta seguro que desea salir del sistema?") == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventoActionPerformed
        DlgBuscarEvento obj = new DlgBuscarEvento(null, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnEventoActionPerformed

    private void btnNuevoMovEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoMovEfectivoActionPerformed
        DlgMovEfectivo obj = new DlgMovEfectivo(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnNuevoMovEfectivoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        DlgUsuario obj = new DlgUsuario(null, true);
        obj.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnConsultarMovEfectivoTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarMovEfectivoTopActionPerformed
        DlgConsultaMovEfectivo obj = new DlgConsultaMovEfectivo(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnConsultarMovEfectivoTopActionPerformed

    private void btnCatalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogosActionPerformed
        //-220
        if (this.panelMenu.getX() == 0) {
            Animacion.Animacion.mover_izquierda(0, -185, 10, 5, this.panelMenu);
//            Animacion.Animacion.mover_izquierda(190, 0, 10, 5, this.btnMenu);
        } else {
            Animacion.Animacion.mover_derecha(this.panelMenu.getX(), 0, 10, 5, this.panelMenu);
//            Animacion.Animacion.mover_derecha(0, 190, 10, 5, this.btnMenu);
        }
    }//GEN-LAST:event_btnCatalogosActionPerformed

    private void btnBautizoTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBautizoTopActionPerformed
        DlgBautizo obj = new DlgBautizo(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnBautizoTopActionPerformed

    private void btnConfirmacionTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmacionTopActionPerformed
        DlgConfirmacion obj = new DlgConfirmacion(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnConfirmacionTopActionPerformed

    private void btnBodaTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBodaTopActionPerformed
        DlgBoda obj = new DlgBoda(this, false);
        obj.setUsuarioLogeado(this.usuario);
        obj.setVisible(true);
    }//GEN-LAST:event_btnBodaTopActionPerformed

    private void btnSalirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseMoved
        this.btnSalir.setBackground(new java.awt.Color(45, 151, 254));
    }//GEN-LAST:event_btnSalirMouseMoved

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.btnSalir.setBackground(new java.awt.Color(0, 129, 255));
    }//GEN-LAST:event_btnSalirMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBautizoTop;
    private javax.swing.JButton btnBodaTop;
    private javax.swing.JButton btnCatalogos;
    private javax.swing.JButton btnComunidad;
    private javax.swing.JButton btnConfirmacionTop;
    private javax.swing.JButton btnConsultaPersonas;
    private javax.swing.JButton btnConsultarMovEfectivoTop;
    private javax.swing.JButton btnEvento;
    private javax.swing.JButton btnJustificacion;
    private javax.swing.JButton btnLugar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNuevoMovEfectivo;
    private javax.swing.JButton btnPersona1;
    private javax.swing.JButton btnSacerdotes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSector;
    private javax.swing.JButton btnTipoSacramento;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblIconUser;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
