/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iglesia.views;

import com.iglesia.controllers.JustificacionController;
import com.iglesia.controllers.MovimientoController;
import com.iglesia.entities.Evento;
import com.iglesia.entities.Justificacion;
import com.iglesia.entities.Movimiento;
import com.iglesia.utils.ProjectUtils;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author remsf
 */
public class PnlMovEfectivo extends javax.swing.JPanel {

    private MovimientoController movimientoController;
    private JustificacionController justificacionController;
    private List<String> excepciones = new ArrayList<>();
    private Movimiento selectedMov;

    public Movimiento getSelectedMov() {
        return selectedMov;        
    }
    
    /**
     * Creates new form PnlMovEfectivo
     */
    public PnlMovEfectivo() {
        initComponents();
        this.movimientoController = new MovimientoController();
        this.justificacionController = new JustificacionController();
        this.jdFechaMov.requestFocus();
        this.cbestado.setSelected(true);        
        this.justificacionController.getComboBox(this.cbJustificacion);
        this.selectedMov = new Movimiento();
        this.txtid.setVisible(false);
        this.movimientoController.getComboTipoMov(this.cbTipoMovimiento);
    }
    
    private void crear() {
        this.excepciones.add("id");
        if (ProjectUtils.validarVacios(this, this.excepciones)) {
            JOptionPane.showMessageDialog(this, "Campo(s) Requerido(s) vacio(s)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.cargarDatos();
        if (!this.movimientoController.crear()) {
            JOptionPane.showMessageDialog(this, "Ocurrio un problema.!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Registro guardado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        ProjectUtils.limpiarComponentes(this);
    }

    private void actualizar() {
        if (ProjectUtils.validarVacios(this, this.excepciones)) {
            JOptionPane.showMessageDialog(this, "Campo(s) Requerido(s) vacio(s)", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.cargarDatos();
        if (!this.movimientoController.actualizar()) {
            JOptionPane.showMessageDialog(this, "Ocurrio un problema.!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JOptionPane.showMessageDialog(this, "Registro modificado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        ProjectUtils.limpiarComponentes(this);
    }
    
    private void cargarDatos(){
        this.selectedMov.setId((this.txtid.getText().equals("")) ? null : Integer.parseInt(this.txtid.getText()));
        this.selectedMov.setFechaMov(this.jdFechaMov.getDate());
        this.selectedMov.setMonto(new BigDecimal(this.txtMonto.getText()));
        this.selectedMov.setTipo(this.cbTipoMovimiento.getSelectedItem().toString());
        this.selectedMov.setIdJustificacion((Justificacion) this.cbJustificacion.getSelectedItem());        
        this.selectedMov.setEstado(this.cbestado.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsMonto = new javax.swing.JSeparator();
        jsEvento = new javax.swing.JSeparator();
        txtid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbestado = new javax.swing.JCheckBox();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jdFechaMov = new com.toedter.calendar.JDateChooser();
        cbJustificacion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarEvento = new javax.swing.JButton();
        btnEliminarEvento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbTipoMovimiento = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(820, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jsMonto.setForeground(new java.awt.Color(0, 0, 0));
        add(jsMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 180, -1));

        jsEvento.setForeground(new java.awt.Color(0, 0, 0));
        add(jsEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, -1));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setForeground(new java.awt.Color(0, 0, 0));
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtid.setName("id"); // NOI18N
        add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 60, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(107, 117, 125));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movimientos de Efectivo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 820, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(107, 117, 125));
        jLabel2.setText("Evento");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(107, 117, 125));
        jLabel3.setText("Monto");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.setBorder(null);
        txtMonto.setName("Apellido"); // NOI18N
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(107, 117, 125));
        jLabel4.setText("Tipo movimiento");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        txtEvento.setEditable(false);
        txtEvento.setBackground(new java.awt.Color(255, 255, 255));
        txtEvento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEvento.setForeground(new java.awt.Color(0, 0, 0));
        txtEvento.setBorder(null);
        add(txtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 270, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(107, 117, 125));
        jLabel6.setText("Estado");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        cbestado.setBackground(new java.awt.Color(255, 255, 255));
        cbestado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbestado.setForeground(new java.awt.Color(107, 117, 125));
        cbestado.setText("Activo");
        add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        btnguardar.setBackground(new java.awt.Color(0, 129, 255));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/save.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setOpaque(true);
        btnguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnguardarMouseMoved(evt);
            }
        });
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 130, 40));

        btncancelar.setBackground(new java.awt.Color(254, 192, 1));
        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/cancel.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setBorder(null);
        btncancelar.setBorderPainted(false);
        btncancelar.setContentAreaFilled(false);
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.setOpaque(true);
        btncancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btncancelarMouseMoved(evt);
            }
        });
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncancelarMouseExited(evt);
            }
        });
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 130, 40));

        jdFechaMov.setBackground(new java.awt.Color(255, 255, 255));
        jdFechaMov.setForeground(new java.awt.Color(55, 71, 79));
        jdFechaMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        add(jdFechaMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, 30));

        cbJustificacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbJustificacion.setBorder(null);
        add(cbJustificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 270, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(107, 117, 125));
        jLabel5.setText("Fecha");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        btnBuscarEvento.setBackground(new java.awt.Color(107, 117, 125));
        btnBuscarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/buscar.png"))); // NOI18N
        btnBuscarEvento.setToolTipText("Buscar evento");
        btnBuscarEvento.setBorder(null);
        btnBuscarEvento.setBorderPainted(false);
        btnBuscarEvento.setContentAreaFilled(false);
        btnBuscarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEvento.setOpaque(true);
        btnBuscarEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarEventoMouseMoved(evt);
            }
        });
        btnBuscarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarEventoMouseExited(evt);
            }
        });
        btnBuscarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEventoActionPerformed(evt);
            }
        });
        add(btnBuscarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 30, 30));

        btnEliminarEvento.setBackground(new java.awt.Color(222, 62, 68));
        btnEliminarEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/images/icon/delete.png"))); // NOI18N
        btnEliminarEvento.setToolTipText("Quitar Evento");
        btnEliminarEvento.setBorder(null);
        btnEliminarEvento.setBorderPainted(false);
        btnEliminarEvento.setContentAreaFilled(false);
        btnEliminarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEvento.setOpaque(true);
        btnEliminarEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEliminarEventoMouseMoved(evt);
            }
        });
        btnEliminarEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarEventoMouseExited(evt);
            }
        });
        btnEliminarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEventoActionPerformed(evt);
            }
        });
        add(btnEliminarEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 30, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(107, 117, 125));
        jLabel7.setText("Justificación");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        cbTipoMovimiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbTipoMovimiento.setBorder(null);
        add(cbTipoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            //            JOptionPane.showMessageDialog(this, "Solo numeros");
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void btnguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseMoved
        this.btnguardar.setBackground(new java.awt.Color(45, 151, 254));
    }//GEN-LAST:event_btnguardarMouseMoved

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        this.btnguardar.setBackground(new java.awt.Color(0, 129, 255));
    }//GEN-LAST:event_btnguardarMouseExited

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (this.txtid.getText().trim().equals("")) {
            this.crear();
        } else {
            this.actualizar();
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseMoved
        this.btncancelar.setBackground(new java.awt.Color(254, 203, 46));
    }//GEN-LAST:event_btncancelarMouseMoved

    private void btncancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseExited
        this.btncancelar.setBackground(new java.awt.Color(254, 192, 1));
    }//GEN-LAST:event_btncancelarMouseExited

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
//        ProjectUtils.limpiarComponentes(this.jPanel1);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnBuscarEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEventoMouseMoved
        this.btnBuscarEvento.setBackground(new java.awt.Color(132, 142, 149));
    }//GEN-LAST:event_btnBuscarEventoMouseMoved

    private void btnBuscarEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEventoMouseExited
        this.btnBuscarEvento.setBackground(new java.awt.Color(107, 117, 125));
    }//GEN-LAST:event_btnBuscarEventoMouseExited

    private void btnBuscarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEventoActionPerformed
        DlgBuscarEvento obj = new DlgBuscarEvento(null, true);
        obj.setVisible(true);
        if (obj.getEvento() != null) {
            Evento evento = obj.getEvento();
            String s = evento.getIdTipoSacramento().getNombre() + ", Folio " + evento.getFolio() + ", número " + evento.getNumero();
            this.selectedMov.setIdEvento(evento);
            this.txtEvento.setText(s);
        }
    }//GEN-LAST:event_btnBuscarEventoActionPerformed

    private void btnEliminarEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEventoMouseMoved
        this.btnEliminarEvento.setBackground(new java.awt.Color(227, 96, 101));
    }//GEN-LAST:event_btnEliminarEventoMouseMoved

    private void btnEliminarEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEventoMouseExited
        this.btnEliminarEvento.setBackground(new java.awt.Color(222, 62, 68));
    }//GEN-LAST:event_btnEliminarEventoMouseExited

    private void btnEliminarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEventoActionPerformed
        this.movimientoController.getSelected().setIdEvento(null);
        this.txtEvento.setText("");
    }//GEN-LAST:event_btnEliminarEventoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEvento;
    private javax.swing.JButton btnEliminarEvento;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<Justificacion> cbJustificacion;
    private javax.swing.JComboBox<String> cbTipoMovimiento;
    private javax.swing.JCheckBox cbestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser jdFechaMov;
    private javax.swing.JSeparator jsEvento;
    private javax.swing.JSeparator jsMonto;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
